Repository streamethorg/streameth-platform, pull requests merged in 2024-08, with the labels that each got.

#840 📝 Improved README.md
  README.md
Labels: documentation, medium priority

#823 ✨ Twitter upload integration
  packages/app/app/studio/[organization]/destinations/page.tsx
  packages/server/src/dtos/session/upload-session.dto.ts
  packages/server/src/interfaces/upload.session.interface.ts
  packages/server/src/routes/routes.ts
  packages/server/src/services/session.service.ts
  packages/server/src/swagger/swagger.json
  packages/video-uploader/package.json
  packages/video-uploader/src/utils/twitter.ts
  packages/video-uploader/src/utils/youtube.ts
  packages/video-uploader/src/video-queue.ts
  yarn.lock
Labels: enhancement

#854 🐛 #853 videos with no assetid giving 404
  packages/app/app/[organization]/watch/page.tsx
  packages/app/app/embed/page.tsx
  packages/app/app/studio/[organization]/library/[session]/page.tsx
  packages/app/app/studio/[organization]/library/components/DeleteAsset.tsx
  packages/app/app/studio/[organization]/library/components/TableCells.tsx
  packages/app/app/studio/[organization]/library/components/misc/PopoverActions.tsx
  packages/app/app/studio/[organization]/library/components/misc/ProcessingSkeleton.tsx
  packages/app/app/studio/[organization]/library/page.tsx
  packages/app/components/misc/ConnectWalletButton.tsx
  packages/app/lib/actions/livepeer.ts
  packages/server/src/routes/routes.ts
  packages/server/src/swagger/swagger.json
Labels: bug, high priority

#855 ⚡Display video processing error in the App
  packages/app/app/studio/[organization]/library/components/LibraryGridLayout.tsx
  packages/app/app/studio/[organization]/library/components/misc/PopoverActions.tsx
  packages/app/app/studio/[organization]/library/components/misc/VideoCardWithMenu.tsx
  packages/app/app/studio/[organization]/nfts/create/components/SelectedMediaItem.tsx
  packages/app/components/misc/VideoCard/VideoCardProcessing.tsx
  packages/app/components/misc/VideoCard/VideoCardWithMenu.tsx
  packages/app/components/misc/VideoCard/index.tsx
  packages/app/lib/hooks/useGenerateThumbnail.ts
Labels: enhancement

#878 ✨ Speaker page
  packages/app/app/api/google/callback/route.ts
  packages/app/app/speaker/[session]/components/ClientSidePlayer.tsx
  packages/app/app/speaker/[session]/components/SpeakerYoutubePublishButton.tsx
  packages/app/app/speaker/[session]/components/ZoraUploadButton.tsx
  packages/app/app/speaker/[session]/page.tsx
  packages/app/app/studio/[organization]/livestreams/[streamId]/components/StreamPlatforms/CreateYoutubeStream.tsx
  packages/app/components/sessions/CollectVideButton.tsx
  packages/app/components/sessions/SessionInfoBox.tsx
  packages/app/lib/data.ts
  packages/app/lib/types.ts
  packages/app/package.json
  packages/server/src/dtos/session/upload-session.dto.ts
  packages/server/src/interfaces/upload.session.interface.ts
  packages/server/src/routes/routes.ts
  packages/server/src/services/session.service.ts
  packages/server/src/swagger/swagger.json
  yarn.lock
Labels: enhancement, high priority

#898 ⚡Replace UpdateAt with CreatedAt and update clipping date
  packages/app/app/studio/[organization]/clips/components/CreateClipButton.tsx
  packages/app/app/studio/[organization]/library/components/LibraryListLayout.tsx
  packages/app/app/studio/[organization]/library/components/TableCells.tsx
  packages/app/app/studio/[organization]/library/components/misc/VideoCardWithMenu.tsx
  packages/app/app/studio/[organization]/library/page.tsx
  packages/app/lib/utils/utils.ts
  packages/server/src/dtos/session/update-session.dto.ts
  packages/server/src/interfaces/session.interface.ts
  packages/server/src/models/session.model.ts
  packages/server/src/routes/routes.ts
  packages/server/src/swagger/swagger.json
  packages/server/src/utils/livepeer.ts
Labels: enhancement

#849 ✨ Implement Backend Logic for Video Processing and Subtitle Addition Using Livepeer Video AI
  packages/app/app/[organization]/watch/page.tsx
  packages/app/app/studio/[organization]/library/[session]/components/SessionTranscriptions.tsx
  packages/app/app/studio/[organization]/library/[session]/page.tsx
  packages/app/components/ui/Player.tsx
  packages/app/lib/actions/sessions.ts
  packages/app/lib/services/sessionService.ts
  packages/app/lib/types.ts
  packages/app/lib/utils/utils.ts
  packages/app/next.config.js
  packages/server/src/controllers/index.controller.ts
  packages/server/src/controllers/session.controller.ts
  packages/server/src/routes/routes.ts
  packages/server/src/services/session.service.ts
  packages/server/src/swagger/swagger.json
  packages/video-uploader/package.json
  packages/video-uploader/src/audio-queue.ts
  packages/video-uploader/src/utils/ffmpeg.ts
  packages/video-uploader/src/utils/helper.ts
  packages/video-uploader/src/utils/logger.ts
  packages/video-uploader/src/utils/mq.ts
  packages/video-uploader/src/utils/twitter.ts
  packages/video-uploader/src/utils/youtube.ts
  packages/video-uploader/src/video-queue.ts
Labels: enhancement

#917 🐛 fix Publish stream error
  packages/app/lib/services/stageService.tsx
Labels: bug

#913 🐛 904 bug no burger items in navbar on mobile in channel page
  packages/app/components/Layout/HomePageNavbar.tsx
  packages/server/src/swagger/swagger.json
Labels: bug, medium priority
