Repository streamethorg/streameth-platform, pull requests merged in 2024-07, with the labels that each got.

#682 Minor bug fixes
  packages/app/app/[organization]/videos/components/ArchiveVideos.tsx
  packages/app/app/studio/(home)/components/CreateOrganizationForm.tsx
  packages/app/app/studio/(home)/page.tsx
  packages/app/app/studio/[organization]/library/components/LibraryListLayout.tsx
  packages/app/app/studio/[organization]/livestreams/components/CreateLivestreamModal.tsx
  packages/app/app/studio/[organization]/livestreams/components/EditLivestream.tsx
  packages/app/app/studio/[organization]/page.tsx
  packages/app/app/studio/[organization]/team/page.tsx
  packages/app/components/misc/Support/SupportForm.tsx
  packages/app/components/misc/form/imageUpload.tsx
  packages/app/components/ui/dialog.tsx
  packages/app/lib/schema.ts
Labels: bug

#613 Update Minting flow and delete Collection page
  packages/app/app/[organization]/collection/components/CollectionGrid.tsx
  packages/app/app/[organization]/collection/page.tsx
  packages/app/app/[organization]/livestream/page.tsx
  packages/app/app/[organization]/page.tsx
  packages/app/app/studio/[organization]/nfts/[nftId]/components/ContractDetails.tsx
  packages/app/app/studio/[organization]/nfts/[nftId]/page.tsx
  packages/app/app/studio/[organization]/nfts/components/NFTCollectionCard.tsx
  packages/app/app/studio/[organization]/nfts/create/components/TransactionHash.tsx
  packages/app/components/Sidebar/SidebarMenu.tsx
  packages/app/components/misc/CopyText.tsx
  packages/app/components/misc/VideoCard/LivestreamCard.tsx
  packages/app/components/sessions/CollectVideButton.tsx
  packages/app/components/sessions/SessionInfoBox.tsx
  packages/app/components/ui/TitleTextItem.tsx
  packages/app/lib/contract/index.ts
  packages/app/lib/types.ts
  packages/app/lib/utils/utils.ts
  packages/contracts/README.md
  packages/contracts/contracts/VideoNFT.sol
  packages/contracts/hardhat.config.ts
  packages/server/src/services/session.service.ts
Labels: in progress

#701 🐛 fix livestream share bug
  packages/app/app/[organization]/livestream/page.tsx
  packages/app/app/studio/[organization]/library/[session]/components/UploadToYoutubeButton.tsx
  packages/app/app/studio/[organization]/livestreams/[streamId]/page.tsx
  packages/app/lib/actions/sessions.ts
  packages/app/lib/services/sessionService.ts
Labels: bug

#708 Generic PR template
  .github/PULL_REQUEST_TEMPLATE/generic_pr.md
  .github/PULL_REQUEST_TEMPLATE/post_mortem.md
Labels: documentation

#718 ✨ Rework of the embed page and Streameth logo on player
  packages/app/app/[organization]/livestream/components/Player.tsx
  packages/app/app/[organization]/watch/page.tsx
  packages/app/app/embed/page.tsx
  packages/app/app/studio/[organization]/library/[session]/components/SessionOptions.tsx
  packages/app/app/studio/[organization]/library/[session]/page.tsx
  packages/app/app/studio/[organization]/livestreams/[streamId]/components/LivestreamEmbedCode.tsx
  packages/app/app/studio/[organization]/livestreams/[streamId]/page.tsx
  packages/app/components/Layout/HomePageNavbar.tsx
  packages/app/components/misc/VideoDownloadClient.tsx
  packages/app/components/misc/interact/EmbedButton.tsx
  packages/app/components/ui/Player.tsx
  packages/app/lib/actions/sessions.ts
  packages/app/lib/services/sessionService.ts
  packages/app/lib/types.ts
  packages/app/lib/utils/utils.ts
  packages/server/src/controllers/index.controller.ts
  packages/server/src/dtos/session/create-session.dto.ts
  packages/server/src/interfaces/session.interface.ts
  packages/server/src/models/session.model.ts
  packages/server/src/routes/routes.ts
  packages/server/src/swagger/swagger.json
  packages/server/src/utils/livepeer.ts
Labels: enhancement

#726 🐛 Docs button misalignment in sidebar
  packages/app/components/Sidebar/Sidebar.tsx
  packages/app/components/Sidebar/SidebarMenu.tsx
Labels: bug, low priority

#724 🥅 Better error pages
  packages/app/app/[organization]/watch/page.tsx
  packages/app/app/error.tsx
  packages/app/app/not-found.tsx
  packages/app/components/Layout/HomePageNavbar.tsx
  packages/app/components/misc/VideoDownloadClient.tsx
  packages/app/components/ui/Player.tsx
  packages/app/lib/actions/sessions.ts
  packages/app/not-found.tsx
  packages/server/src/routes/routes.ts
  packages/server/src/swagger/swagger.json
Labels: enhancement

#758 🐛 fix comboBox items not been selected
  packages/app/components/ui/combo-box.tsx
Labels: bug

#753 ✨ Studio library Pagination, Filter and SearchBar
  packages/app/app/[organization]/videos/components/pagination.tsx
  packages/app/app/studio/[organization]/library/components/LibraryFilter.tsx
  packages/app/app/studio/[organization]/library/components/UploadVideoDialog.tsx
  packages/app/app/studio/[organization]/library/page.tsx
  packages/app/app/studio/[organization]/page.tsx
  packages/app/components/misc/SearchBar/index.tsx
  packages/app/components/ui/button.tsx
  packages/app/components/ui/checkbox.tsx
  packages/app/lib/data.ts
  packages/app/lib/hooks/useSearchParams.ts
  packages/server/src/controllers/session.controller.ts
  packages/server/src/routes/routes.ts
  packages/server/src/services/session.service.ts
  packages/server/src/swagger/swagger.json
Labels: enhancement

#773 🐛 fix metadata w/o cover image on watch page
  packages/app/app/(vod)/watch/page.tsx
  packages/app/app/[organization]/watch/page.tsx
  packages/app/components/misc/VideoCard/VideoCardWithMenu.tsx
  packages/app/lib/utils/metadata.ts
  packages/server/src/routes/routes.ts
Labels: bug

#765 🐛 Fixed z indexes
  packages/app/app/[organization]/page.tsx
  packages/app/components/Layout/HomePageNavbar.tsx
Labels: bug

#766 🐛 Fix the sign-in flow getting stuck when quickly clicking sign-out
  packages/app/components/misc/SignInUserButton.tsx
Labels: bug

#794 📝 Updated issues and PR templates
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE/generic_pr.md
  .github/PULL_REQUEST_TEMPLATE/post_mortem.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  packages/app/components/ui/Player.tsx
Labels: low priority

#806 💄: Revert - Show Library Delete Buttons & Hide Social upload buttons
  packages/app/app/studio/[organization]/library/[session]/components/EditSessionForm.tsx
  packages/app/app/studio/[organization]/library/[session]/components/UploadToYoutubeButton.tsx
  packages/app/app/studio/[organization]/library/components/misc/PopoverActions.tsx
  packages/app/components/Sidebar/SidebarMenu.tsx
  packages/app/components/ui/Player.tsx
Labels: medium priority

#814 🐛 Fixes #728 + some more enhancements
  packages/app/app/studio/(home)/components/CreateOrganizationForm.tsx
  packages/app/components/misc/form/imageUpload.tsx
  packages/app/components/ui/Player.tsx
Labels: medium priority

#819 🐛 Fixes #818
  packages/app/components/misc/form/imageUpload.tsx
Labels: medium priority

#817 ⚡fixes #746 App takes you to login screen after being logged in for a while
  packages/app/components/authorization/CheckAuthorization.tsx
  packages/app/components/misc/SignInUserButton.tsx
  packages/app/package.json
Labels: bug, high priority
