Repository streamethorg/streameth-platform, pull requests merged in 2024-06, with the labels that each got.

#638 📝 post-mortem template for PRs
  .github/PULL_REQUEST_TEMPLATE/post-mortem.md
Labels: documentation

#647 🚚: Rename post-mortem.md to pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#643 youtube integrations part 1
  packages/app/app/api/google/callback/route.ts
  packages/app/app/studio/[organization]/library/[session]/components/UploadToYoutubeButton.tsx
  packages/app/app/studio/[organization]/library/[session]/page.tsx
  packages/app/lib/actions/sessions.ts
  packages/app/lib/services/organizationService.tsx
  packages/app/lib/services/sessionService.ts
  packages/app/lib/types.ts
  packages/app/lib/utils/googleAuth.ts
  packages/server/src/config/index.ts
  packages/server/src/controllers/organization.controller.ts
  packages/server/src/controllers/session.controller.ts
  packages/server/src/dtos/organization/create-organization.dto.ts
  packages/server/src/interfaces/organization.interface.ts
  packages/server/src/models/organization.model.ts
  packages/server/src/routes/routes.ts
  packages/server/src/services/organization.service.ts
  packages/server/src/swagger/swagger.json
  packages/server/src/utils/oauth.ts
  packages/server/src/utils/youtube.ts
Labels: enhancement

#674 🛠️ EthCC server config
  packages/app/app/studio/[organization]/clips/page.tsx
  packages/server/package.json
  packages/server/src/config/index.ts
  packages/server/src/controllers/index.controller.ts
  packages/server/src/dtos/session/create-session.dto.ts
  packages/server/src/interfaces/session.interface.ts
  packages/server/src/models/session.model.ts
  packages/server/src/routes/routes.ts
  packages/server/src/swagger/swagger.json
  packages/server/src/utils/firebase.ts
  packages/server/src/utils/livepeer.ts
  packages/server/src/utils/validateEnv.ts
  yarn.lock
Labels: enhancement

#673 Fix #661 by using watch API from react-hook-form
  package-lock.json
  packages/app/app/studio/[organization]/livestreams/[streamId]/page.tsx
  packages/app/app/studio/[organization]/livestreams/components/CreateLivestreamModal.tsx
  yarn.lock
Labels: bug

#681 ⚡ Update clip session items to ComboBox(Implement search by input)
  packages/app/app/studio/[organization]/clips/components/CreateClipButton.tsx
  packages/app/components/ui/combo-box.tsx
Labels: bug
